openapi: 3.0.1
info:
  title: GanApp API
  description: GanApp API specification
  version: "0.1"
servers:
- url: http://54.217.5.65:3000
- url: http://localhost:4000
paths:
  /products:
    get:
      description: Gets all the products
      responses:
        "200":
          description: Success
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples:
                All products:
                  value:
                  - amount: 2
                    _id: some-id
                    name: patates
                    dateAdded: 2020-07-03T11:52:41.998Z
                    __v: 0
                  - amount: 3
                    _id: some-other-id
                    name: dracs
                    dateAdded: 2020-07-03T11:52:41.998Z
                    __v: 0
    post:
      description: Auto generated using Swagger Inspector
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
            examples:
              only specifying name:
                value: |-
                  {
                      "name": "some-product-name"
                  }
      responses:
        "401":
          description: Auto generated using Swagger Inspector
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples: {}
  /products/{id}:
    get:
      description: Gets the specific product
      parameters:
      - name: id
        in: path
        description: The id of the product to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples:
                A specific product:
                  value:
                    amount: 2
                    _id: some-id
                    name: patates
                    dateAdded: 2020-07-03T11:52:41.998Z
                    __v: 0
    put:
      description: Updates the specific product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
            examples:
              updates the name:
                value: |-
                  {
                      "name": "new-name"
                  }
      parameters:
      - name: id
        in: path
        description: The id of the product to update
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples:
                A specific product:
                  value:
                    amount: 2
                    _id: some-id
                    name: patates
                    dateAdded: 2020-07-03T11:52:41.998Z
                    __v: 0
    delete:
      description: Deletes the specific product
      parameters:
      - name: id
        in: path
        description: The id of the product to delete
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples:
                Delete successful:
                  value:
                    message: Product [cheese] was succesfully deleted.
components:
  schemas:
    product:
      type: object
      properties:
        name:
          type: string